### ISSUE TITLE
Fax - polyphonic suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [RCameron93/FehlerFabrik#3]
Hi! Could you make fax polyphonic? I'd like to record up to 8 voices simultaneously with it.

**Comment by RCameron93** [comment]
[I've created a new branch](https://github.com/RCameron93/FehlerFabrik/tree/polyphony) with this feature.

In it's default behaviour,  Fax will now record and output as many channels as are currently connected to it's Input. Via the context menu, you can also set it to constantly output up to 16 channels, regardless of how many are actually connected at that time. 

When recording, if input is monophonic/using the knob, the recorded voltage for channel 1 is duplicated to all other channels. If polyphonic, but still less than 16 channels are being recorded, the remaining channels will be overwritten to 0V. 

I've also added persistence, so stored voltages should remain when you reload a patch.

This is the first time I've added polyphony to a module, and I think it's quite a weird one to start off with. I've also not had a lot of time to test this one which is why I've added it as a branch, Please let me know if there's any bugs, or if you think it's behaviour could be improved.
