### ISSUE TITLE
feature request: add mod index to Psi Op

### ISSUE THREAD

**Issue by glocke01** [RCameron93/FehlerFabrik#6]
Cool modules! Having fun with them. 

I suppose this is intentional, but there doesn't seem to be any want to control the amount of modulation on Psi Op aside from the release time for the modulator. Ratio and algorithm have an effect, but, basically, you're getting a very pronounced click whatever you do.

**Comment by RCameron93** [comment]
It is somewhat intentional yes, the goal with PSI OP was a module that is almost always spitting out gnarly FM. There is a global modulation amount already in the code, it's currently only affected by the presence of a trigger on the Accent input.

I'm set on the modules layout, I won't be adding any new jacks or knobs. Any new features are going to be added via the context menu, and I'd like to keep those to the kind of things that are equivalent to jumper options on a hardware module.

With all that considered, I've [added an option](https://github.com/RCameron93/FehlerFabrik/commit/fbedd1f8fa63f2b0a73a9fd924e68d2bbc84e666) to control the modulation index via the level of the main trigger. A trigger of 10V will perform as normal, a 2V trigger will only have 20% modulation, with the obvious sliding scale in between those values. Triggers still need to be at least 2V, so 20% is the lowest index possible.

This is just going to stay on the development branch for now, I want to sit with it for a while before I decide to merge it with the released version.

**Comment by RCameron93** [comment]
This feature will be added in the new version, so I'm closing this.
